framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true

    session:
        enabled: true
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 86400
        gc_maxlifetime: 1800
        cookie_httponly: true

    #esi: true
    #fragments: true
    php_errors:
        log: true
