security:
    providers:
        app_user_provider:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            logout:
                path:   app_logout
                target: /
                invalidate_session: true
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginAuthenticator
    access_control:
      # - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/main|/profile|/filter|/band, roles: ROLE_USER }
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }