twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    globals:
        date_time_provider: '@App\Services\DataProvider\DateTimeProvider'