#index:
#    path: /
#    controller: App\Controller\DefaultController::index

loginIndex:
  path: /
  controller: App\Controller\LoginController:loginIndex

mainIndex:
  path: /main
  controller: App\Controller\MainController:mainIndexAction