loginIndex:
  path: /
  controller: App\Controller\LoginController:loginIndex

mainIndex:
  path: /main
  controller: App\Controller\MainController:mainIndexAction

registerUser:
  path: /register_user
  controller: App\Controller\RegistrationController:registerUserAction
  methods: POST

sendAuthenticationLink:
  path: /send_authentication
  controller: App\Controller\MailController:sendRegisterMailAction
  methods: POST

authenticateAccount:
  path: /authenticate_account/{username}/{authenticationLink}
  controller: App\Controller\SecurityController:authenticateAccountAction

sendChangePasswordAction:
  path: /send_change_password_email
  controller: App\Controller\MailController:sendChangePasswordAction
  methods: POST

changePasswordIndex:
  path: /change_password/{userId}/{changePasswordLink}
  controller: App\Controller\LoginController:changePasswordIndexAction

changePasswordAction:
  path: /change_password
  controller: App\Controller\LoginController:changePasswordAction
  methods: POST

profileIndexAction:
  path: /profile/{username}
  controller: App\Controller\ProfileController:indexAction
  methods: GET

profileEditAction:
  path: /profile/{username}/edit
  controller: App\Controller\ProfileController:editIndexAction
  methods: GET

profileEditBasicInfo:
  path: /profile/edit/basic_info
  controller: App\Controller\ProfileController:editProfileAction
  methods: POST

getCurrentUserInstruments:
  path: /profile/edit/instruments
  controller: App\Controller\ProfileController:getCurrentUserInstrumentsAction
  methods: GET

getCurrentUserMusicGenres:
  path: /profile/edit/musicGenres
  controller: App\Controller\ProfileController:getCurrentUserMusicGenresAction
  methods: GET

updateCurrentUserInstruments:
  path: /profile/edit/update_instruments
  controller: App\Controller\ProfileController:updateCurrentUserInstrumentsAction
  methods: PUT

updateCurrentUserMusicGenres:
  path: /profile/edit/update_genres
  controller: App\Controller\ProfileController:updateCurrentUserMusicGenresAction
  methods: PUT

filterInstruments:
  path: /filter/instrument/{prefix}/{limit<\d+>?5}
  controller: App\Controller\FilterController:filterInstrumentsAction
  methods: GET

filterMusicGenres:
  path: /filter/musicGenre/{prefix}/{limit<\d+>?5}
  controller: App\Controller\FilterController:filterMusicGenresAction
  methods: GET

filterCity:
  path: /filter/city/{prefix}/{limit<\d+>?5}
  controller: App\Controller\FilterController:filterCitysAction
  methods: GET

instrumentExists:
  path: /filter/instrumentExists/{name}
  controller: App\Controller\FilterController:instrumentExistsAction
  methods: GET

musicGenreExists:
  path: /filter/musicGenreExists/{name}
  controller: App\Controller\FilterController:musicGenreExistsAction
  methods: GET

cityExists:
  path: /filter/cityExists/{name}
  controller: App\Controller\FilterController:cityExistsAction
  methods: GET

userExists:
  path: /userExists/{username}
  controller: App\Controller\FilterController:usernameExistsAction
  methods: GET

usersIndexAction:
  path: /users
  controller: App\Controller\UsersController:indexAction
  methods: GET

createBandIndexAction:
  path: /band/create
  controller: App\Controller\BandController:createIndexAction
  methods: GET

createBandAction:
  path: /band/createNewBand
  controller: App\Controller\BandController:createBandAction
  methods: POST

bandProfileIndexAction:
  path: /band/profile/{bandId}
  controller: App\Controller\BandController:bandProfileIndexAction
  methods: GET

bandsIndexAction:
  path: /bands
  controller: App\Controller\BandController:bandsIndexAction
  methods: GET

noticeCreateIndexAction:
  path: /notice/create
  controller: App\Controller\NoticeController:noticeCreateIndexAction
  methods: GET

searchNoticesIndexAction:
  path: /notices
  controller: App\Controller\NoticeController:indexAction
  methods: GET

createNoticeAction:
  path: /notice/createNewNotice
  controller: App\Controller\NoticeController:createNoticeAction
  methods: POST

createProfilePostAction:
  path: /post/createProfilePost
  controller: App\Controller\PostController:createPostOnProfile
  methods: POST

createBandPostAction:
  path: /band/createPost
  controller: App\Controller\PostController:createPostOnBand
  methods: POST

blockUsersAction:
  path: /profile/edit/update_blockedUsers
  controller: App\Controller\ProfileController:updateCurrentUserBlockedUsers
  methods: PUT

getCurrentUserBlockedUsers:
  path: /profile/edit/blockedUsers
  controller: App\Controller\ProfileController:getCurrentUserBlockedUsersAction
  methods: GET

reportNoticeAction:
  path: /report/reportNotice
  controller: App\Controller\ReportController:reportNoticeAction
  methods: POST

reportPostAction:
  path: /report/reportPost
  controller: App\Controller\ReportController:reportPostAction
  methods: POST

sendMessageAction:
  path: /messages/send
  controller: App\Controller\MessageController:sendMessageToUserAction
  methods: POST

blockUserAction:
  path: /profile/blockUser
  controller: App\Controller\ProfileController:blockUserAction
  methods: POST

editBandAction:
  path: /band/edit
  controller: App\Controller\BandController:editBandAction
  methods: POST

getCurrentBandMusicGenres:
  path: /band/edit/musicGenres/{bandId}
  controller: App\Controller\BandController:getCurrentBandMusicGenres
  methods: GET

sendAddUserToBandMessageAction:
  path: /messages/sendAddUserToBand
  controller: App\Controller\MessageController:sendAddUserToBandMessage
  methods: POST

allMessagesIndexAction:
  path: /messages
  controller: App\Controller\MessageController:allMessagesIndexAction
  methods: GET

messagesIndexAction:
  path: /messages/{userId}
  controller: App\Controller\MessageController:messagesIndexAction
  methods: GET

sendMessageAndRedirectAction:
  path: /messages/send/redirect
  controller: App\Controller\MessageController:sendMessageAndRedirectAction
  methods: POST

addUserToBandAction:
  path: /messages/addUserToBand
  controller: App\Controller\MessageController:decideAddUserToBandMessage
  methods: POST

adminReportsIndexAction:
  path: /admin/reports
  controller: App\Controller\AdminController:adminReportsIndexAction
  methods: GET

adminBansIndexAction:
  path: /admin/bans
  controller: App\Controller\AdminController:adminBansIndexAction
  methods: GET

adminCancelReportAction:
  path: /admin/cancelReport
  controller: App\Controller\AdminController:cancelReportAction
  methods: PATCH

adminBanUserAction:
  path: /admin/banUser
  controller: App\Controller\AdminController:blockUserAction
  methods: PATCH

deleteItemAction:
  path: /admin/deleteItem
  controller: App\Controller\AdminController:deleteItemAction
  methods: POST

unbanUserAction:
  path: /admin/unbanUser
  controller: App\Controller\AdminController:unbanUserAction
  methods: PATCH

adminSendNewsletter:
  path: /admin/newsletter
  controller: App\Controller\AdminController:adminSendNewsletterAction
  methods: POST