loginIndex:
  path: /
  controller: App\Controller\LoginController:loginIndex

mainIndex:
  path: /main
  controller: App\Controller\MainController:mainIndexAction

registerUser:
  path: /register_user
  controller: App\Controller\RegistrationController:registerUserAction
  methods: POST

sendAuthenticationLink:
  path: /send_authentication
  controller: App\Controller\MailController:sendRegisterMailAction
  methods: POST

authenticateAccount:
  path: /authenticate_account/{username}/{authenticationLink}
  controller: App\Controller\SecurityController:authenticateAccountAction

sendChangePasswordAction:
  path: /send_change_password_email
  controller: App\Controller\MailController:sendChangePasswordAction
  methods: POST

changePasswordIndex:
  path: /change_password/{userId}/{changePasswordLink}
  controller: App\Controller\LoginController:changePasswordIndexAction

changePasswordAction:
  path: /change_password
  controller: App\Controller\LoginController:changePasswordAction
  methods: POST

profileIndexAction:
  path: /profile/{username}
  controller: App\Controller\ProfileController:indexAction
  methods: GET

profileEditAction:
  path: /profile/{username}/edit
  controller: App\Controller\ProfileController:editIndexAction
  methods: GET

profileEditBasicInfo:
  path: /profile/edit/basic_info
  controller: App\Controller\ProfileController:editProfileAction
  methods: POST

getCurrentUserInstruments:
  path: /profile/edit/instruments
  controller: App\Controller\ProfileController:getCurrentUserInstrumentsAction
  methods: GET

getCurrentUserMusicGenres:
  path: /profile/edit/musicGenres
  controller: App\Controller\ProfileController:getCurrentUserMusicGenresAction
  methods: GET

updateCurrentUserInstruments:
  path: /profile/edit/update_instruments
  controller: App\Controller\ProfileController:updateCurrentUserInstrumentsAction
  methods: PUT

updateCurrentUserMusicGenres:
  path: /profile/edit/update_genres
  controller: App\Controller\ProfileController:updateCurrentUserMusicGenresAction
  methods: PUT

filterInstruments:
  path: /filter/instrument/{prefix}/{limit<\d+>?5}
  controller: App\Controller\FilterController:filterInstrumentsAction
  methods: GET

filterMusicGenres:
  path: /filter/musicGenre/{prefix}/{limit<\d+>?5}
  controller: App\Controller\FilterController:filterMusicGenresAction
  methods: GET

instrumentExists:
  path: /filter/instrumentExists/{name}
  controller: App\Controller\FilterController:instrumentExistsAction
  methods: GET

musicGenreExists:
  path: /filter/musicGenreExists/{name}
  controller: App\Controller\FilterController:musicGenreExistsAction
  methods: GET

userExists:
  path: /userExists/{username}
  controller: App\Controller\FilterController:usernameExistsAction
  methods: GET

usersIndexAction:
  path: /users
  controller: App\Controller\UsersController:indexAction
  methods: GET

createBandIndexAction:
  path: /band/create
  controller: App\Controller\BandController:createIndexAction
  methods: GET

createBandAction:
  path: /band/createNewBand
  controller: App\Controller\BandController:createBandAction
  methods: POST

bandProfileIndexAction:
  path: /band/profile/{bandId}
  controller: App\Controller\BandController:bandProfileIndexAction
  methods: GET